---
- hosts: mygroup
  remote_user: root
  vars:
    msg: "Welcome to DevOps Apache Home"
    lmsg: "Thank You"
  tasks:
  - name: Deploy Index
    template:
      src: /tmp/index.html
      dest: /mnt/data/index.html
